version: '3.9'

services:
  app:
    build: ./app
    ports:
      - "8080:80"
    environment:
      DB_HOST: db
      DB_DATABASE: multipro_support
      DB_USER: multipro
      DB_PASSWORD: multipro
      STORAGE_PATH: /var/www/storage
    volumes:
      - ./app:/var/www
    depends_on:
      - db

  db:
    image: mariadb:11.2
    restart: unless-stopped
    environment:
      MARIADB_DATABASE: multipro_support
      MARIADB_USER: multipro
      MARIADB_PASSWORD: multipro
      MARIADB_ROOT_PASSWORD: rootpassword
    volumes:
      - db_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

volumes:
  db_data:
